spring:
  application:
    name: jasapro-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/jasapro_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  web:
    resources:
      add-mappings: false  # Disable automatic static resource mapping

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.jasapro: DEBUG
    com.jasapro.backend.modules.provider: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    org.springframework.beans.factory.support.DefaultListableBeanFactory: DEBUG
    org.springframework.context.support.PostProcessorRegistrationDelegate: DEBUG
    org.hibernate.SQL: DEBUG
